.gitignore, composer.json, phpunit.xml.dist
=> Initial set up

.travis.yml, composer.json, tests/SampleTest.php
=> Setting up Travis CI

tests/Fixtures.php, tests/Fixtures/SampleClass.php, tests/Fixtures/fixture_config.json, tests/Fixtures/fixture_config.php, tests/Fixtures/fixture_config.yml, tests/Fixtures/fixture_sample.json, tests/Fixtures/fixture_sample.yml
@mortaliorchard @OrCharles
Added fixtures classes and files:
config files hold a sample config for loggers.
sample files hold some random dummy json or yaml
SampleClass is a dummy class Monolog Cascade loader is going to load in its tests
Fixtures.php is a util class to access various fixtures.
=> Added fixtures classes and files

src/Config/ConfigLoader.php, tests/Config/ConfigLoaderTest.php
This is the main config loader it would load a php array, Yaml file, JSON file, Yaml string, JSON string
Will add .ini in the future.
@mortaliorchard @OrCharles
=> Base config file loader

examples/logger_config.json, examples/logger_config.yml, examples/multiple_loggers.php, examples/single_logger.php
Basic examples:
- one using only the registry and `MonoLogger::getLogger()`
- another one using the entire feature set: loading formatters, handlers and loggers
@mortaliorchard @OrCharles
=> Adding some examples

.coveralls.yml, .travis.yml, composer.json
=> Added test coverage with Coveralls + added dependencies in composer.json

composer.json
Fix the Travis build for HHVM
@mortaliorchard
=> Fixed build for HHVM

src/Config.php, src/Config/Loader/ClassLoader/ProcessorLoader.php, tests/Config/Loader/ClassLoader/ProcessorLoaderTest.php
Added code to support the use of processors per channel.
=> Support for processors per channel

src/Cascade.php, src/Config.php
@rantonmattei I fixed a few issues with param types for better type hinting.
=> Fixed IO param types for proper type hinting.

tests/Fixtures/fixture_config.json, tests/Fixtures/fixture_config.php
Removed some leftover from Python port.
=> Fixed fixture files with propoer class and param names

README.md, examples/logger_config.yml
=> Added more supporting documentation and examples for procesors

composer.json
=> Bumped up a few packages especially Symfony 2.8

.coveralls.yml
Removed src_dir value causing coveralls to error out.
@jessmchung
=> Removed src_dir value

.travis.yml
Make coveralls more verbose to figure out why it is no reporting back to GH
=> Make coveralls more verbose

composer.json
=> Prepared release

composer.json
Seen, someone already did it. But he change the ownership of the project.
Becouse he didn't fix it since september, my pull request might be helpful.
=> support symfony 3

README.md
Added link to Medium post in ReadMe
=> Added link to Medium post in ReadMe

src/Cascade.php, src/Config.php, src/Config/Loader/ClassLoader/FormatterLoader.php, src/Config/Loader/ClassLoader/HandlerLoader.php, src/Config/Loader/ClassLoader/LoggerLoader.php, src/Config/Loader/ClassLoader/ProcessorLoader.php, src/Config/Loader/ClassLoader/Resolver/ExtraOptionsResolver.php, tests/CascadeTest.php, tests/Config/Loader/ClassLoader/FormatterLoaderTest.php, tests/Config/Loader/ClassLoader/HandlerLoaderTest.php, tests/Config/Loader/ClassLoader/LoggerLoaderTest.php, tests/Config/Loader/ClassLoader/Resolver/ConstructorResolverTest.php, tests/Config/Loader/ClassLoader/Resolver/ExtraOptionsResolverTest.php, tests/Config/Loader/FileLoader/FileLoaderAbstractTest.php, tests/Fixtures/SampleClass.php
@jessmchung as wished here's the first part of the splitted PR #71.
=> Several phpdoc fixes

src/Cascade.php, tests/CascadeTest.php, tests/Fixtures.php
@jessmchung And here's the other part of #71. I only hope I didn't made any mistakes by splitting that PR ;-)
=> Added aliases for Cascade::fileConfig

.travis.yml, composer.json
This change will allow to install Monolog Cascade alongside with symfony4.
=> Add support for symfony4

src/Config/Loader/FileLoader/Json.php
=> fix issue #78

README.md
See issue https://github.com/theorchard/monolog-cascade/issues/84
=> fixed logger name in README.md example
